### ISSUE TITLE
[Bug] Crash when selecting disconnected rail secments

### ISSUE THREAD

**Issue by TDietrich99** [fgardt/factorio-rail-decon-planner#3] opened 2023-09-26 11:12 UTC
```
The mod Rail Deconstruction Planner (1.0.2) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event rail-decon-planner::on_player_selected_area (ID 51)
LuaEntity API call when LuaEntity was invalid.
stack traceback:
	[C]: in function '__index'
	__rail-decon-planner__/control.lua:241: in function 'mark_segments'
	__rail-decon-planner__/control.lua:333: in function <__rail-decon-planner__/control.lua:330>
```

**Comment by fgardt** [comment] 2023-09-26 19:20
Invalid entity? Interesting. Do you maybe have something that would instantly delete things marked for deconstruction?

I added checks that should catch any cases of other mods invalidating entities while I still expected them to be valid in 43269601551d3de2b54de6e92db8f1219224a044 (released in 1.0.3).

Thanks again for reporting this!

**Closed as completed by fgardt** 2023-09-26 19:20 UTC

**Comment by TDietrich99** [comment] 2023-09-26 19:45
No problem. this mod is one of the QOL mods that i would hate to miss out on. 

would it be possible to make it work with ghost also? or mixed ghost/real sections? i know there are no options for deconstruction ghosts but you could just remove them right?

**Comment by fgardt** [comment] 2023-09-27 05:55
The issue is that the functionality requires the rail to be actual rail entities. These provide the functions to retrieve the segments used to traverse the rail.

To support the same for ghost rails I'd need to reimplement all of the connection searches by doing position based entity searches (not even speaking of signals & stations).
A way around this could be to search for ghost rails/signals/stations in a radius around a entity and turn those into "real" ones to reuse the existing traversal.
Then afterwards turn all non removed rails/signals/stations back to ghosts and remove all others.

It's really hacky and other mods could interfere at any point since these conversions always immediately trigger events for all mods and they could do things and mess around (which caused this issue probably).

I'll think about it, but before that I should probably add per-player settings to configure the tool a bit more (remove stations on/off, remove signals on/off (?), remove specific tile below tracks off/tile-select/all(?)). And probably more important a way to just mark a single block instead of the sometimes very far traversal (probably by doing reverse selections by holding rightclick instead of leftclick).
